### ISSUE TITLE
Why does val need indirection for functions?

### ISSUE THREAD

**Issue by averynortonsmith** [ameerwasi001/Closkell#1]
In the documentation, why does assigning a variable to a lambda function using `val`look like this `val add = \ -> \a -> \b -> a+b`, rather than `val add = \a -> \b -> a+b`? Would the second version not work? Or is the example written this way to preserve semantic equivalence with the `let` example?

**Comment by averynortonsmith** [comment]
Neat language by the way! The idea of variables that look like functions reminds me of [this discussion](https://www.reddit.com/r/ProgrammingLanguages/comments/h8m4i6/do_any_languages_have_a_feature_that_lets_a/), and inheritance reminds me a bit of [Pyret](https://www.pyret.org/index.html).

**Comment by ameerwasi001** [comment]
Oh sorry, I was not able to see this issue in time but here I finally somehow got my eye on it. About the indirection, it is in no way needed but this is how `curry` keyword does it, so in order to meet the exact semantic for explanation purposes, I decided to write it this way in the documentation.

The `curry` keyword is supposed to define a regular "function variable"(I just mean a lambda attached to a "variable") since variables are themselves functions it just followed that functions inside variables would be functions inside functions. So to summarize it was done for consistency's sake.

Also, I see that you mentioned Pyret which was a huge inspiration for this language thus having a similar inheritance model and sum types.

**Comment by averynortonsmith** [comment]
I see, makes sense.

That's cool that you had Pyret in mind when thinking about the design! I guess the world of PLs designed for education is still relatively small.
